package rtdtserver

import (
	"sync/atomic"
	"time"
)

// payment tracks the data for a payment that is being redeemed.
type payment struct {
	// bytesAllowance is the running allowance that hasn't been redeemed
	// from this payment.
	bytesAllowance atomic.Int64

	// tag is the original payment tag generated by brserver.
	tag uint64

	// endTime is when this payment expires and can no longer be redeemed.
	endTime time.Time
}
