run:
  deadline: 15m

linters:
  build-tags:
    - e2elegacylntest

  disable-all: true
  enable:
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - sqlclosecheck
    - unconvert
    - unused
