run:
  deadline: 15m

linters:
  build-tags:
    - e2elegacylntest

  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errchkjson
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - typecheck
    - unconvert
    - unused
    - vetshadow
    - wastedassign
