version: "2"
run:
  build-tags:
    - e2elegacylntest
    - dcrlnde2e
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errchkjson
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - protoc-gen-go-svcintf
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
