package rpc

import (
	"github.com/companyzero/bisonrelay/zkidentity"
)

// CreateRTDTSession is a PRPC command to create a new RTDT session on brserver.
type CreateRTDTSession struct {
	// Size is the max number of concurrent users in the session. This
	// determines the payment rates for the session.
	Size uint32 `json:"size"`
}

// CreateRTDTSessionReply is the PRPC reply to CreateRTDTSession.
type CreateRTDTSessionReply struct {
	// SessionCookie is opaque session data that identifies the session.
	SessionCookie []byte `json:"session_cookie"`
}

// RTDTAppointmentCookiePeer is one peer for which an appointment cookie is
// requested.
type RTDTAppointmentCookiePeer struct {
	// ID is the RTDT peer id.
	ID RTDTPeerID `json:"id"`

	// AllowedAsPublisher is true if the peer is allowed as publisher in
	// the session.
	AllowedAsPublisher bool `json:"allowed_as_publisher"`

	// IsAdmin is true if the passed peer id is allowed as admin of the
	// session.
	IsAdmin bool `json:"is_admin"`
}

// GetRTDTAppointCookies is a PRPC command that an RTDT session owner or admin
// uses to get a list of appointment cookies from brserver for clients to use
// to join an RTDT session.
type GetRTDTAppointCookies struct {
	// SessionCookie is the opaque session cookie created by the
	// CreateRTDTSession PRPC.
	SessionCookie []byte `json:"session_cookie"`

	// OwnerSecret is random data from the session owner. This is used as
	// part of the unique session id in the RTDT server.
	//
	// Using the same SessionCookie with different OwnerSecret values will
	// put users in different RTDT sessions.
	OwnerSecret zkidentity.ShortID `json:"owner_secret"`

	// Peers is the list of peers for which an appointment cookie is
	// requested.
	Peers []RTDTAppointmentCookiePeer `json:"peers"`

	// OldOwnerSecret is the prior owner secret for this session. When
	// specified, the server generates a rotation cookie to be used to
	// perform a live session id rotation.
	OldOwnerSecret *zkidentity.ShortID `json:"old_owner_secret"`
}

// GetRTDTAppointCookiesReply is the set of appointment cookie replies from the
// server.
type GetRTDTAppointCookiesReply struct {
	// AppointCookies are the appointment cookies for the peer ids passed
	// in the GetAppointCookies PRPC command.
	AppointCookies [][]byte `json:"appoint_cookies"`

	// RotateCookie is the rotate cookie created when rotating the
	// appointment cookies.
	RotateCookie []byte `json:"rotate_cookie"`
}

// AppointRTDTServer is the PRPC command sent by a client to enable it to join
// and (optionally) send data in an RTDT session.
type AppointRTDTServer struct {
	// AppointCookie is the peer's appointment cookie, generated by the
	// session owner/admin.
	AppointCookie []byte `json:"appoint_cookie"`
}

// AppointRTDTServerReply is the reply to a previous AppointRTDTServer command.
type AppointRTDTServerReply struct {
	// JoinCookie is the opaque join cookie the client should use to join
	// the RTDT server.
	JoinCookie []byte `json:"join_cookie"`

	// ServerAddress is the address (FQDN or IP and port) of the RTDT server
	// the client should use to join.
	ServerAddress string `json:"server_address"`

	// ServerPubKey is the public key of the RTDT server. If nil, the server
	// does not use client/server encryption (data is sent in plaintext).
	ServerPubKey *zkidentity.FixedSizeSntrupPublicKey `json:"server_pubkey"`
}
