package rpc

import (
	"github.com/companyzero/bisonrelay/zkidentity"
)

// RMCRTDTSessionInvite is the command for the RMRTDTSessionInvite C2C message.
const RMCRTDTSessionInvite = "rtdtsessinvite"

// RMRTDTSessionInvite is the routed message sent from the RTDT session/owner
// to a remote client to invite it to a session.
type RMRTDTSessionInvite struct {
	// RV is the session RV.
	RV zkidentity.ShortID `json:"rv"`

	// AppointCookie is generated by the server to the session owner/admin
	// and shared with the target client.
	AppointCookie []byte `json:"appoint_cookie"`

	// Size is the max number of users in the session.
	Size uint32 `json:"size"`

	// Description is a brief description of the session.
	Description string `json:"description"`

	// AllowedAsPublisher flags whether the client will be allowed to send
	// data in the session. When this is false, the client can only receive
	// data from other publishers ("spectate").
	AllowedAsPublisher bool `json:"allowed_as_publisher"`

	// PeerID is the peer id the client should use when sending realtime
	// data.
	PeerID RTDTPeerID `json:"peer_id"`

	// GC is filled if this session is to be associated with a particular
	// GC.
	GC *zkidentity.ShortID `json:"gc"`

	// Tag identifies this invite.
	Tag uint64 `json:"tag"`
}

// RMCRTDTSessionInviteAccept is the command for the RMRTDTSessionPublisher C2C
// message.
const RMCRTDTSessionInviteAccept = "rtdtsessinviteaccept"

// RMRTDTSessionInviteAccept is the routed message of the invitee accepting the
// invitation to join an RTDTSession.
type RMRTDTSessionInviteAccept struct {
	// RV is the RV of the session.
	RV zkidentity.ShortID `json:"rv"`

	// Tag must match the tag in the invitation.
	Tag uint64 `json:"tag"`

	// PublisherKey should be set if the client will send data in the
	// session.
	PublisherKey *zkidentity.FixedSizeSymmetricKey `json:"publisher_key"`
}

// RMRTDTSessionPublisher tracks information about a client that sends data in
// a RTDT session.
type RMRTDTSessionPublisher struct {
	// PublisherID is the user ID of the client.
	PublisherID zkidentity.ShortID `json:"publisher_id"`

	// PeerID is the realtime id of messages sent by the client.
	PeerID RTDTPeerID `json:"peer_id"`

	// PublisherKey is the key to decrypt messages from this peer.
	PublisherKey zkidentity.FixedSizeSymmetricKey `json:"publisher_key"`

	// Alias is the user's nick.
	Alias string `json:"alias"`
}

// RMCRTDTSession is the command for the RMRTDTSession C2C meessage.
const RMCRTDTSession = "rtdtsession"

// RMRTDTSession is the routed message that updates a client about changes in an
// RTDT session. This comes from the owner/admin of the session.
type RMRTDTSession struct {
	// Generation is increased on every change to the session.
	Generation uint32 `json:"generation"`

	// RV is the unique session identifier.
	RV zkidentity.ShortID `json:"rv"`

	// Size is the max number of concurrent users in the session.
	Size uint32 `json:"size"`

	// Description is a small description of the session.
	Description string `json:"description"`

	// Owner is the user ID of the owner of the session.
	Owner zkidentity.ShortID `json:"owner"`

	// Admins is a list of admins of the session.
	Admins []zkidentity.ShortID `json:"admins"`

	// Publishers is a list of users allowed to publish data in the
	// session.
	Publishers []RMRTDTSessionPublisher `json:"publishers"`
}

// IsOwnerOrAdmin returns true if the given ID is the owner or an admin of the
// session.
func (sess *RMRTDTSession) IsOwnerOrAdmin(id zkidentity.ShortID) bool {
	if sess.Owner == id {
		return true
	}

	for i := range sess.Admins {
		if sess.Admins[i] == id {
			return true
		}
	}

	return false
}

// AllAdmins returns the list of all admins (including owner) of the session.
func (sess *RMRTDTSession) AllAdmins() []zkidentity.ShortID {
	return append(sess.Admins, sess.Owner)
}

// RMCRTDTExitSession is the command for the RMRTDTExitSession C2C meessage.
const RMCRTDTExitSesssion = "rtdtexitsess"

// RMRTDTExitSession is a routed message sent from a member that wishes to
// permanently leave an RTDT session.
type RMRTDTExitSession struct {
	RV zkidentity.ShortID `json:"rv"`
}

// RMCRTDTDissolveSession is the command for the RMRTDTDissolveSession C2C
// meessage.
const RMCRTDTDissolveSesssion = "rtdtdisssess"

// RMRTDTDissolveSession is a routed message sent from the RTDT session owner
// when they are dissolving the session.
type RMRTDTDissolveSession struct {
	RV zkidentity.ShortID `json:"rv"`
}

// RMCRTDTRemovedFromSession is the command for the RMRTDTRemovedFromSession
// C2C meessage.
const RMCRTDTRemovedFromSession = "rtdtremovedfromsess"

// RMRTDTRemovedFromSession is a routed message sent from an RTDT session admin
// when a client was forcibly removed.
type RMRTDTRemovedFromSession struct {
	RV     zkidentity.ShortID `json:"rv"`
	Reason string             `json:"reason"`
}

// RMCRTDTRotateAppointCookie is the command for the RMRTDTRotateAppointCookie
// C2C meessage.
const RMCRTDTRotateAppointCookie = "rtdtrotappointcookie"

// RMRTDTRotateAppointCookie is a routed message sent from an RTDT session admin
// when the appointment cookie of the user was rotated to a new one.
type RMRTDTRotateAppointCookie struct {
	RV            zkidentity.ShortID `json:"rv"`
	AppointCookie []byte             `json:"appoint_cookie"`
}

// RMCRTDTAdminCookies is the command for the RMRTDTAdminCookies C2C message.
const RMCRTDTAdminCookies = "rtdtadmincookies"

// RMRTDTAdminMember is one member of a session, with metadata required by
// session admins.
type RMRTDTAdminMember struct {
	UID                zkidentity.ShortID `json:"uid"`
	PeerID             RTDTPeerID         `json:"peer_id"`
	AppointCookie      []byte             `json:"appoint_cookie"`
	AllowedAsPublisher bool               `json:"allowed_as_publisher"`
}

// RMRTDTAdminCookies is a routed message sent from an RTDT session admin to
// other (new) admins to share the details of a (potentially new) session cookie,
// owner secret and appointment cookies.
type RMRTDTAdminCookies struct {
	RV            zkidentity.ShortID  `json:"rv"`
	SessionCookie []byte              `json:"session_cookie"`
	OwnerSecret   *zkidentity.ShortID `json:"owner_secret"`
	Members       []RMRTDTAdminMember `json:"members"`
	NextPeerID    *RTDTPeerID         `json:"next_peer_id"`
}
