// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: pluginrpc.proto

package grpctypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginStartStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *PluginStartStreamRequest) Reset() {
	*x = PluginStartStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginStartStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStartStreamRequest) ProtoMessage() {}

func (x *PluginStartStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStartStreamRequest.ProtoReflect.Descriptor instead.
func (*PluginStartStreamRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{0}
}

func (x *PluginStartStreamRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PluginStartStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Started      bool   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	PlayerNumber int32  `protobuf:"varint,2,opt,name=player_number,json=playerNumber,proto3" json:"player_number,omitempty"` // Player 1 or Player 2
	Message      string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                // Confirmation message or additional details
	ClientId     string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *PluginStartStreamResponse) Reset() {
	*x = PluginStartStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginStartStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStartStreamResponse) ProtoMessage() {}

func (x *PluginStartStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStartStreamResponse.ProtoReflect.Descriptor instead.
func (*PluginStartStreamResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{1}
}

func (x *PluginStartStreamResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *PluginStartStreamResponse) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

func (x *PluginStartStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginStartStreamResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PluginVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PluginVersionRequest) Reset() {
	*x = PluginVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginVersionRequest) ProtoMessage() {}

func (x *PluginVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginVersionRequest.ProtoReflect.Descriptor instead.
func (*PluginVersionRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{2}
}

// VersionResponse is the information about the running RPC server.
type PluginVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// app_version is the version of the application.
	AppVersion string `protobuf:"bytes,1,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// go_runtime is the Go version the server was compiled with.
	GoRuntime string `protobuf:"bytes,2,opt,name=go_runtime,json=goRuntime,proto3" json:"go_runtime,omitempty"`
	// app_name is the name of the underlying app running the server.
	AppName string `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *PluginVersionResponse) Reset() {
	*x = PluginVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginVersionResponse) ProtoMessage() {}

func (x *PluginVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginVersionResponse.ProtoReflect.Descriptor instead.
func (*PluginVersionResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{3}
}

func (x *PluginVersionResponse) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *PluginVersionResponse) GetGoRuntime() string {
	if x != nil {
		return x.GoRuntime
	}
	return ""
}

func (x *PluginVersionResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type PluginCallActionStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PluginCallActionStreamRequest) Reset() {
	*x = PluginCallActionStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginCallActionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCallActionStreamRequest) ProtoMessage() {}

func (x *PluginCallActionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCallActionStreamRequest.ProtoReflect.Descriptor instead.
func (*PluginCallActionStreamRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{4}
}

func (x *PluginCallActionStreamRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PluginCallActionStreamRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginCallActionStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PluginCallActionStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PluginCallActionStreamResponse) Reset() {
	*x = PluginCallActionStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginCallActionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCallActionStreamResponse) ProtoMessage() {}

func (x *PluginCallActionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCallActionStreamResponse.ProtoReflect.Descriptor instead.
func (*PluginCallActionStreamResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{5}
}

func (x *PluginCallActionStreamResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type PluginCallActionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateMessage string `protobuf:"bytes,1,opt,name=update_message,json=updateMessage,proto3" json:"update_message,omitempty"`
}

func (x *PluginCallActionUpdate) Reset() {
	*x = PluginCallActionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginCallActionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCallActionUpdate) ProtoMessage() {}

func (x *PluginCallActionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCallActionUpdate.ProtoReflect.Descriptor instead.
func (*PluginCallActionUpdate) Descriptor() ([]byte, []int) {
	return file_pluginrpc_proto_rawDescGZIP(), []int{6}
}

func (x *PluginCallActionUpdate) GetUpdateMessage() string {
	if x != nil {
		return x.UpdateMessage
	}
	return ""
}

var File_pluginrpc_proto protoreflect.FileDescriptor

var file_pluginrpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x37, 0x0a, 0x18, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x19, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x16,
	0x0a, 0x14, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x15, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x1d, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x1e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x16, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xde, 0x01, 0x0a, 0x0d, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x04,
	0x49, 0x6e, 0x69, 0x74, 0x12, 0x19, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4f, 0x0a,
	0x0a, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3b,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x7a, 0x65, 0x72, 0x6f, 0x2f, 0x62, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x72, 0x65, 0x6c, 0x61,
	0x79, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pluginrpc_proto_rawDescOnce sync.Once
	file_pluginrpc_proto_rawDescData = file_pluginrpc_proto_rawDesc
)

func file_pluginrpc_proto_rawDescGZIP() []byte {
	file_pluginrpc_proto_rawDescOnce.Do(func() {
		file_pluginrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pluginrpc_proto_rawDescData)
	})
	return file_pluginrpc_proto_rawDescData
}

var file_pluginrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pluginrpc_proto_goTypes = []interface{}{
	(*PluginStartStreamRequest)(nil),       // 0: PluginStartStreamRequest
	(*PluginStartStreamResponse)(nil),      // 1: PluginStartStreamResponse
	(*PluginVersionRequest)(nil),           // 2: PluginVersionRequest
	(*PluginVersionResponse)(nil),          // 3: PluginVersionResponse
	(*PluginCallActionStreamRequest)(nil),  // 4: PluginCallActionStreamRequest
	(*PluginCallActionStreamResponse)(nil), // 5: PluginCallActionStreamResponse
	(*PluginCallActionUpdate)(nil),         // 6: PluginCallActionUpdate
}
var file_pluginrpc_proto_depIdxs = []int32{
	0, // 0: PluginService.Init:input_type -> PluginStartStreamRequest
	4, // 1: PluginService.CallAction:input_type -> PluginCallActionStreamRequest
	2, // 2: PluginService.GetVersion:input_type -> PluginVersionRequest
	1, // 3: PluginService.Init:output_type -> PluginStartStreamResponse
	5, // 4: PluginService.CallAction:output_type -> PluginCallActionStreamResponse
	3, // 5: PluginService.GetVersion:output_type -> PluginVersionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pluginrpc_proto_init() }
func file_pluginrpc_proto_init() {
	if File_pluginrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pluginrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginStartStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginStartStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginCallActionStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginCallActionStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginCallActionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pluginrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginrpc_proto_goTypes,
		DependencyIndexes: file_pluginrpc_proto_depIdxs,
		MessageInfos:      file_pluginrpc_proto_msgTypes,
	}.Build()
	File_pluginrpc_proto = out.File
	file_pluginrpc_proto_rawDesc = nil
	file_pluginrpc_proto_goTypes = nil
	file_pluginrpc_proto_depIdxs = nil
}
