name: Build CGOless brclient
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Build CGOless brclient
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.23"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build
        run: go build ./...
        env:
          CGO_ENABLED: 0
